spring:
  application:
    name: APIGateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**, /api/health/**, /api/user/**
          filters:
            - name: AuthenticationFilter
        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/api/chat/**
          filters:
            - name: AuthenticationFilter
              args:
                empty: '' # or just empty: true, if your filter expects a boolean

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
